### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by robinpecha** [weebi/micro-preview#3]
Hi, your plugin looks promising but Im not able to install it on Ubuntu 22.04.2 LTS:

```
$ micro --version
Version: 2.0.11

$ cat .config/micro/settings.json
{
    "autosave": 1,
    "colorscheme": "dukelight-tc",
    "pluginrepos": [
        "https://raw.githubusercontent.com/weebi/micro-preview/master/repo.json"
    ],
    "softwrap": true,
    "tabsize": 5
}

$ micro -plugin install preview
Error installing  preview :  unable to find a matching version for "preview"

```
Please what Im doing worng.

**Comment by weebi** [comment]
It looks like the Ubuntu repositories are still a little behind...
This plugin was originally written using the latest versions of Micro, which is why I only supported those versions. 

But I've tested it now on some older versions, and pushed a fix for this in [c2eb9e2](https://github.com/weebi/micro-preview/commit/c2eb9e2aae22efa8a589c801df24d941a317d5d1).
It should now work for you too, thanks for the report!
